server:
  port: 8085

eureka:
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${server.port}-${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5

spring:
  jackson:
    serialization:
      indent_output: true

endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false
