server:
  port: 8085

info:
  id: @pom.artifactId@
  version: @project.version@
  description: Admin service

endpoints:
  health:
    sensitive: false

spring:
  application:
    name: @pom.artifactId@
  boot:
    admin:
      url: http://localhost:8085
